import { Agent, LifecycleEvent } from './types';

export const mockAgents: Agent[] = [
  { id: 'a1', name: 'Alice', role: 'Project Manager', domain: 'Management', skills: ['Planning', 'Coordination'], lifecycle: 'persistent' },
  { id: 'a2', name: 'Bob', role: 'Frontend Lead', parentId: 'a1', domain: 'Frontend', skills: ['React', 'WebGL'], lifecycle: 'persistent' },
  { id: 'a3', name: 'Charlie', role: 'Backend Lead', parentId: 'a1', domain: 'Backend', skills: ['Node.js', 'Database'], lifecycle: 'persistent' },
  { id: 'a4', name: 'E2E Test Runner', role: 'QA Engineer', parentId: 'a1', domain: 'Testing', skills: ['E2E', 'Performance'], lifecycle: 'contract', workspace: 'Staging Env' },
  { id: 'a5', name: 'Asset Scraper', role: 'Resource Fetcher', parentId: 'a2', domain: 'Tools', skills: ['Scraping', 'Assets'], lifecycle: 'ephemeral', workspace: 'Figma' },
  { id: 'a6', name: 'Doc Search', role: 'Search Agent', parentId: 'a3', domain: 'Research', skills: ['Web Search'], lifecycle: 'ephemeral', workspace: 'Notion' },
  { id: 'a7', name: 'Web Search', role: 'Search Agent', parentId: 'a3', domain: 'Research', skills: ['Web Search'], lifecycle: 'ephemeral', workspace: 'Browser' },
  { id: 'a8', name: 'Crash Analyzer', role: 'Debugger', parentId: 'a2', domain: 'Frontend', skills: ['Debugging'], lifecycle: 'ephemeral', workspace: 'Sentry' },
  { id: 'a9', name: 'DB Migrator', role: 'Database Admin', parentId: 'a3', domain: 'Backend', skills: ['SQL', 'Migrations'], lifecycle: 'ephemeral', workspace: 'Postgres' },
  { id: 'a10', name: 'UI Tester', role: 'QA Engineer', parentId: 'a4', domain: 'Testing', skills: ['Cypress', 'Playwright'], lifecycle: 'ephemeral', workspace: 'Browser' },
  { id: 'a11', name: 'Security Scanner', role: 'SecOps', parentId: 'a1', domain: 'Security', skills: ['Audit', 'SAST'], lifecycle: 'contract', workspace: 'CI/CD' },
  { id: 'a12', name: 'Load Tester', role: 'Performance Engineer', parentId: 'a3', domain: 'Testing', skills: ['k6', 'JMeter'], lifecycle: 'ephemeral', workspace: 'AWS' },
  { id: 'a13', name: 'A/B Test Configurator', role: 'Growth', parentId: 'a2', domain: 'Frontend', skills: ['Optimizely', 'Analytics'], lifecycle: 'ephemeral', workspace: 'Dashboard' },
  { id: 'a14', name: 'Data Pipeline Builder', role: 'Data Engineer', parentId: 'a3', domain: 'Backend', skills: ['Airflow', 'Python'], lifecycle: 'contract', workspace: 'GCP' },
  { id: 'a15', name: 'I18n Translator', role: 'Localization', parentId: 'a2', domain: 'Frontend', skills: ['Translation', 'i18next'], lifecycle: 'ephemeral', workspace: 'Lokalise' },
  { id: 'a16', name: 'DevOps Bot', role: 'Infrastructure', parentId: 'a1', domain: 'Management', skills: ['Terraform', 'Kubernetes'], lifecycle: 'persistent', workspace: 'AWS' },
  { id: 'a17', name: 'Log Monitor', role: 'SRE', parentId: 'a16', domain: 'Security', skills: ['Datadog', 'Splunk'], lifecycle: 'ephemeral', workspace: 'Datadog' },
  { id: 'a18', name: 'Cache Optimizer', role: 'Backend Engineer', parentId: 'a3', domain: 'Backend', skills: ['Redis', 'Memcached'], lifecycle: 'ephemeral', workspace: 'Redis' },
  { id: 'a19', name: 'Accessibility Checker', role: 'A11y Expert', parentId: 'a2', domain: 'Frontend', skills: ['Axe', 'WCAG'], lifecycle: 'ephemeral', workspace: 'Browser' },
  { id: 'a20', name: 'Release Manager', role: 'Release Coordinator', parentId: 'a1', domain: 'Management', skills: ['GitHub Actions', 'Jira'], lifecycle: 'contract', workspace: 'GitHub' },
];

export const mockEvents: LifecycleEvent[] = [
  { id: 'e1', agentId: 'a1', timestamp: 0, type: 'spawn' },
  { id: 'e2', agentId: 'a1', timestamp: 5, type: 'start' },
  { id: 'e3', agentId: 'a1', timestamp: 15, type: 'split', targetId: 'a2' },
  { id: 'e4', agentId: 'a1', timestamp: 15, type: 'split', targetId: 'a3' },
  { id: 'e5', agentId: 'a2', timestamp: 15, type: 'spawn' },
  { id: 'e6', agentId: 'a3', timestamp: 15, type: 'spawn' },
  { id: 'e7', agentId: 'a2', timestamp: 20, type: 'start' },
  { id: 'e8', agentId: 'a3', timestamp: 20, type: 'start' },
  { id: 'e9', agentId: 'a2', timestamp: 35, type: 'split', targetId: 'a5' },
  { id: 'e10', agentId: 'a5', timestamp: 35, type: 'spawn' },
  { id: 'e11', agentId: 'a5', timestamp: 40, type: 'start' },
  { id: 'e12', agentId: 'a3', timestamp: 45, type: 'split', targetId: 'a6' },
  { id: 'e13', agentId: 'a3', timestamp: 45, type: 'split', targetId: 'a7' },
  { id: 'e14', agentId: 'a6', timestamp: 45, type: 'spawn' },
  { id: 'e15', agentId: 'a7', timestamp: 45, type: 'spawn' },
  { id: 'e16', agentId: 'a6', timestamp: 50, type: 'start' },
  { id: 'e17', agentId: 'a7', timestamp: 50, type: 'start' },
  { id: 'e18', agentId: 'a6', timestamp: 70, type: 'merge', targetId: 'a3' },
  { id: 'e19', agentId: 'a7', timestamp: 75, type: 'merge', targetId: 'a3' },
  { id: 'e20', agentId: 'a6', timestamp: 72, type: 'archive' },
  { id: 'e21', agentId: 'a7', timestamp: 77, type: 'archive' },
  { id: 'e22', agentId: 'a5', timestamp: 80, type: 'merge', targetId: 'a2' },
  { id: 'e23', agentId: 'a5', timestamp: 82, type: 'archive' },
  { id: 'e24', agentId: 'a2', timestamp: 85, type: 'pause', details: 'Waiting for API' },
  { id: 'e25', agentId: 'a3', timestamp: 95, type: 'handoff', targetId: 'a2' },
  { id: 'e26', agentId: 'a2', timestamp: 96, type: 'resume' },
  { id: 'e27', agentId: 'a2', timestamp: 110, type: 'error', details: 'WebGL Context Lost' },
  { id: 'e28', agentId: 'a2', timestamp: 115, type: 'split', targetId: 'a8' },
  { id: 'e29', agentId: 'a8', timestamp: 115, type: 'spawn' },
  { id: 'e30', agentId: 'a8', timestamp: 120, type: 'start' },
  { id: 'e31', agentId: 'a8', timestamp: 140, type: 'merge', targetId: 'a2' },
  { id: 'e32', agentId: 'a8', timestamp: 142, type: 'archive' },
  { id: 'e33', agentId: 'a2', timestamp: 145, type: 'resume' },
  { id: 'e34', agentId: 'a2', timestamp: 160, type: 'pause' },
  { id: 'e35', agentId: 'a3', timestamp: 160, type: 'pause' },
  { id: 'e36', agentId: 'a1', timestamp: 165, type: 'split', targetId: 'a4' },
  { id: 'e37', agentId: 'a4', timestamp: 165, type: 'spawn' },
  { id: 'e38', agentId: 'a4', timestamp: 170, type: 'start' },
  { id: 'e39', agentId: 'a3', timestamp: 100, type: 'split', targetId: 'a9' },
  { id: 'e40', agentId: 'a9', timestamp: 100, type: 'spawn' },
  { id: 'e41', agentId: 'a9', timestamp: 105, type: 'start' },
  { id: 'e42', agentId: 'a9', timestamp: 125, type: 'merge', targetId: 'a3' },
  { id: 'e43', agentId: 'a9', timestamp: 128, type: 'archive' },
  { id: 'e44', agentId: 'a4', timestamp: 175, type: 'split', targetId: 'a10' },
  { id: 'e45', agentId: 'a10', timestamp: 175, type: 'spawn' },
  { id: 'e46', agentId: 'a10', timestamp: 180, type: 'start' },
  { id: 'e47', agentId: 'a1', timestamp: 20, type: 'split', targetId: 'a11' },
  { id: 'e48', agentId: 'a11', timestamp: 20, type: 'spawn' },
  { id: 'e49', agentId: 'a11', timestamp: 25, type: 'start' },
  { id: 'e50', agentId: 'a11', timestamp: 190, type: 'merge', targetId: 'a1' },
  { id: 'e51', agentId: 'a11', timestamp: 195, type: 'archive' },
  { id: 'e52', agentId: 'a10', timestamp: 195, type: 'merge', targetId: 'a4' },
  { id: 'e53', agentId: 'a10', timestamp: 198, type: 'archive' },
  { id: 'e54', agentId: 'a4', timestamp: 199, type: 'merge', targetId: 'a1' },
  { id: 'e55', agentId: 'a4', timestamp: 200, type: 'archive' },
  
  // New events up to 400
  { id: 'e56', agentId: 'a2', timestamp: 205, type: 'resume' },
  { id: 'e57', agentId: 'a3', timestamp: 205, type: 'resume' },
  { id: 'e58', agentId: 'a3', timestamp: 210, type: 'split', targetId: 'a12' },
  { id: 'e59', agentId: 'a12', timestamp: 210, type: 'spawn' },
  { id: 'e60', agentId: 'a12', timestamp: 215, type: 'start' },
  { id: 'e61', agentId: 'a2', timestamp: 220, type: 'split', targetId: 'a13' },
  { id: 'e62', agentId: 'a13', timestamp: 220, type: 'spawn' },
  { id: 'e63', agentId: 'a13', timestamp: 225, type: 'start' },
  { id: 'e64', agentId: 'a3', timestamp: 230, type: 'split', targetId: 'a14' },
  { id: 'e65', agentId: 'a14', timestamp: 230, type: 'spawn' },
  { id: 'e66', agentId: 'a14', timestamp: 235, type: 'start' },
  { id: 'e67', agentId: 'a12', timestamp: 245, type: 'error', details: 'Load Test Failed' },
  { id: 'e68', agentId: 'a12', timestamp: 250, type: 'merge', targetId: 'a3' },
  { id: 'e69', agentId: 'a12', timestamp: 252, type: 'archive' },
  { id: 'e70', agentId: 'a13', timestamp: 260, type: 'merge', targetId: 'a2' },
  { id: 'e71', agentId: 'a13', timestamp: 262, type: 'archive' },
  { id: 'e72', agentId: 'a2', timestamp: 265, type: 'split', targetId: 'a15' },
  { id: 'e73', agentId: 'a15', timestamp: 265, type: 'spawn' },
  { id: 'e74', agentId: 'a15', timestamp: 270, type: 'start' },
  { id: 'e75', agentId: 'a1', timestamp: 275, type: 'split', targetId: 'a16' },
  { id: 'e76', agentId: 'a16', timestamp: 275, type: 'spawn' },
  { id: 'e77', agentId: 'a16', timestamp: 280, type: 'start' },
  { id: 'e78', agentId: 'a16', timestamp: 290, type: 'split', targetId: 'a17' },
  { id: 'e79', agentId: 'a17', timestamp: 290, type: 'spawn' },
  { id: 'e80', agentId: 'a17', timestamp: 295, type: 'start' },
  { id: 'e81', agentId: 'a15', timestamp: 300, type: 'merge', targetId: 'a2' },
  { id: 'e82', agentId: 'a15', timestamp: 302, type: 'archive' },
  { id: 'e83', agentId: 'a3', timestamp: 310, type: 'split', targetId: 'a18' },
  { id: 'e84', agentId: 'a18', timestamp: 310, type: 'spawn' },
  { id: 'e85', agentId: 'a18', timestamp: 315, type: 'start' },
  { id: 'e86', agentId: 'a17', timestamp: 320, type: 'error', details: 'Log Ingestion Timeout' },
  { id: 'e87', agentId: 'a17', timestamp: 325, type: 'merge', targetId: 'a16' },
  { id: 'e88', agentId: 'a17', timestamp: 327, type: 'archive' },
  { id: 'e89', agentId: 'a2', timestamp: 330, type: 'split', targetId: 'a19' },
  { id: 'e90', agentId: 'a19', timestamp: 330, type: 'spawn' },
  { id: 'e91', agentId: 'a19', timestamp: 335, type: 'start' },
  { id: 'e92', agentId: 'a18', timestamp: 345, type: 'merge', targetId: 'a3' },
  { id: 'e93', agentId: 'a18', timestamp: 347, type: 'archive' },
  { id: 'e94', agentId: 'a19', timestamp: 355, type: 'merge', targetId: 'a2' },
  { id: 'e95', agentId: 'a19', timestamp: 357, type: 'archive' },
  { id: 'e96', agentId: 'a1', timestamp: 360, type: 'split', targetId: 'a20' },
  { id: 'e97', agentId: 'a20', timestamp: 360, type: 'spawn' },
  { id: 'e98', agentId: 'a20', timestamp: 365, type: 'start' },
  { id: 'e99', agentId: 'a14', timestamp: 375, type: 'merge', targetId: 'a3' },
  { id: 'e100', agentId: 'a14', timestamp: 377, type: 'archive' },
  { id: 'e101', agentId: 'a20', timestamp: 385, type: 'merge', targetId: 'a1' },
  { id: 'e102', agentId: 'a20', timestamp: 387, type: 'archive' },
  { id: 'e103', agentId: 'a2', timestamp: 390, type: 'pause', details: 'Awaiting Final Review' },
  { id: 'e104', agentId: 'a3', timestamp: 390, type: 'pause', details: 'Awaiting Final Review' },
  { id: 'e105', agentId: 'a16', timestamp: 395, type: 'pause', details: 'Infrastructure Stable' },
];
